### ISSUE TITLE
glove.840B.300d.txt

### ISSUE THREAD

**Issue by EcemSozeri** [1783696285/SKS-master#1]
Hello there,

I examine the article and codes and try to reach the results myself. But the following file does not exist:

glove.840B.300d.txt: "The word embeddings file (Word2Vec format)"

Would you please share?

Thanks.

**Comment by 1783696285** [comment]
The word embeddings file are not required to be Word2Vec format, you don't have to care about the python filenames.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1783696285/SKS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 凌晨2:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[1783696285/SKS] glove.840B.300d.txt (Issue #1)





 
Hello there,
 
I examine the articles and codes and try to reach the results myself. But the following file does not exist:
 
glove.840B.300d.txt: "The word embeddings file (Word2Vec format)"
 
Would you please share?
 It's very important to me.
 Thanks.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
